title: Nauman Ahad
url: "https://nahad3.github.io/"


markdown: kramdown
#ins_logo: "./bits-logo.png"

#tracking_id: #

#footer: yes
#footer_url: "https://github.com/ankitsultana"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "LinkedIn"
   link: "www.linkedin.com/in/nahad3"
 - name: "Resume"
   link: "Resume_Nauman.pdf"
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?hl=en&user=Z-UiPTQAAAAJ"
# - name: "About"
#   link: "/researcher/"

# - name: "Contact"
#   link: "contact"
