title: Nauman Ahad
url: "https://nahad3.github.io/"


markdown: kramdown
#ins_logo: "./bits-logo.png"

#tracking_id: #

#footer: yes
#footer_url: "https://github.com/ankitsultana"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Publications"
   link: "Publications"
 - name: "CV"
   link: "Nauman_CV_website.pdf"
 - name: "Contact"
   link: "contact"
 #- name: "اُردُو"
 #  link: "urdu_test"
# - name: "About"
#   link: "/researcher/"

# - name: "Contact"
#   link: "contact"
