title: Nauman Ahad
url: "https://nahad3.github.io/"


markdown: kramdown
#ins_logo: "./bits-logo.png"

#tracking_id: #

#footer: yes
#footer_url: "https://github.com/ankitsultana"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "Resume_Nauman_5.pdf"
# - name: "About"
#   link: "/researcher/"

# - name: "Contact"
#   link: "contact"
